[package]
name = "cloud-stash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.174"
serde_json = "1.0.103"
thiserror = "1.0.44"
